# 应用名称
spring:
  application:
    name: orange-frame-job
  cloud:
    nacos:
      # 注册服务
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/orange-frame?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.orange.frame.job.entity

server:
  port: 9005

